import { Download, Clock } from 'lucide-react'
import type { GeneratedReport } from '@/types/analytics'
import { Button } from '@/components/ui/button'

interface ReportHistoryProps {
    reports: GeneratedReport[]
}

export function ReportHistory({ reports }: ReportHistoryProps) {
    return (
        <div className="rounded-xl border border-ink-200 bg-paper overflow-hidden shadow-xs space-y-3 text-xs">
            <div className="p-4 border-b border-ink-100 flex items-center justify-between bg-ink-50/40">
                <div className="space-y-0.5">
                    <h3 className="text-sm font-bold text-ink-900 flex items-center gap-2">
                        <Clock className="h-4 w-4 text-terracotta-600" />
                        <span>Statutory Dossier & Parliamentary Digest Archive</span>
                    </h3>
                    <p className="text-[11px] text-ink-500">
                        Historical generated reports, audit digests, and certified executive memorandums
                    </p>
                </div>

                <span className="font-mono text-[11px] text-ink-500 bg-paper px-2 py-0.5 rounded border border-ink-200">
                    {reports.length} Archived Dossiers
                </span>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse text-xs">
                    <thead>
                        <tr className="border-b border-ink-100 bg-ink-50/70 text-[10px] font-bold text-ink-600 uppercase tracking-wider">
                            <th scope="col" className="py-2.5 px-3">Dossier ID & Title</th>
                            <th scope="col" className="py-2.5 px-3">Report Format</th>
                            <th scope="col" className="py-2.5 px-3">Scope & Period</th>
                            <th scope="col" className="py-2.5 px-3">Generated By</th>
                            <th scope="col" className="py-2.5 px-3">Timestamp</th>
                            <th scope="col" className="py-2.5 px-3 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-ink-100">
                        {reports.map((r) => (
                            <tr key={r.id} className="hover:bg-ink-50/50 transition-colors">
                                <td className="py-3 px-3 space-y-0.5">
                                    <span className="font-mono text-[10px] font-bold text-ink-700 bg-ink-100 px-1.5 py-0.2 rounded border border-ink-200">
                                        {r.id}
                                    </span>
                                    <span className="font-semibold text-ink-900 block truncate max-w-[240px]">
                                        {r.title}
                                    </span>
                                </td>

                                <td className="py-3 px-3">
                                    <span className="rounded bg-sky-50 px-2 py-0.5 text-[10px] font-semibold text-sky-800 border border-sky-200 uppercase">
                                        {r.reportType.replace(/_/g, ' ')}
                                    </span>
                                </td>

                                <td className="py-3 px-3 space-y-0.5">
                                    <span className="font-semibold text-ink-800 block truncate max-w-[180px]">
                                        {r.scopeDescription}
                                    </span>
                                    <span className="text-[10px] text-ink-500 font-mono">
                                        {r.reportingPeriod}
                                    </span>
                                </td>

                                <td className="py-3 px-3 text-ink-700 truncate max-w-[150px]">
                                    {r.generatedBy}
                                </td>

                                <td className="py-3 px-3 font-mono text-ink-500 text-[10px]">
                                    {new Date(r.generatedAt).toLocaleString('en-IN')}
                                </td>

                                <td className="py-3 px-3 text-right">
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="sm"
                                        onClick={() => window.print()}
                                        className="h-7 px-2 text-[11px] font-semibold flex items-center gap-1 ml-auto cursor-pointer"
                                    >
                                        <Download className="h-3 w-3 text-signal-700" />
                                        <span>Download</span>
                                    </Button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    )
}
