import * as React from 'react'
import { FileSpreadsheet, FileText, Download, Printer, ShieldCheck } from 'lucide-react'
import type { ReportType, GeneratedReport, AnalyticsFilterState } from '@/types/analytics'
import { useGenerateReportMutation } from '@/hooks/use-analytics'
import { Button } from '@/components/ui/button'

interface ReportBuilderProps {
    filters: AnalyticsFilterState
    onClose?: () => void
}

const REPORT_TYPES: Array<{ type: ReportType; label: string; description: string }> = [
    {
        type: 'EXECUTIVE_SUMMARY',
        label: 'National Executive Summary Brief',
        description: 'Comprehensive high-level statutory milestone progress, land acquisition, and financial burn rate.',
    },
    {
        type: 'PROJECT_PERFORMANCE',
        label: 'Scheme Milestone Delivery & Lifecycle Audit',
        description: 'Detailed corridor-wise performance comparison across acquisition, compensation, and possession.',
    },
    {
        type: 'LAND_ACQUISITION_STATUS',
        label: 'Cadastral Survey & Area Handover Register',
        description: 'Plot-by-plot Section 11 preliminary vs Section 23/30 award handover status.',
    },
    {
        type: 'COMPENSATION_FINANCIAL',
        label: 'Direct Benefit Transfer (DBT) & Award Ledger',
        description: 'PFMS disbursement reconciliation, assessed compensation, and Section 77 escrow deposits.',
    },
    {
        type: 'POSSESSION_HANDOVER',
        label: 'Section 38 Physical Possession Report',
        description: 'Form 22 notice handover certificate status, site demarcation, and agency transfers.',
    },
    {
        type: 'R_AND_R_RESETTLEMENT',
        label: 'Second Schedule Rehabilitation & Resettlement Audit',
        description: 'Census of affected households, housing grant allotments, and subsistence allowances.',
    },
    {
        type: 'WORKFLOW_SLA_AUDIT',
        label: 'Administrative Task SLA & Citizen Charter Audit',
        description: 'Review officer turnaround latency, pending review queues, and statutory breach analysis.',
    },
    {
        type: 'DISTRICT_JURISDICTION',
        label: 'District Revenue Jurisdiction Comparative Matrix',
        description: 'District Collectorate acquisition throughput and dispute concentration ranking.',
    },
]

export function ReportBuilder({ filters, onClose }: ReportBuilderProps) {
    const [selectedType, setSelectedType] = React.useState<ReportType>('EXECUTIVE_SUMMARY')
    const [generatedReport, setGeneratedReport] = React.useState<GeneratedReport | null>(null)
    const generateMutation = useGenerateReportMutation()

    const handleGenerate = () => {
        generateMutation.mutate(
            { reportType: selectedType, filters },
            {
                onSuccess: (report) => {
                    setGeneratedReport(report)
                },
            },
        )
    }

    const handlePrint = () => {
        window.print()
    }

    const handleExportCSV = () => {
        if (!generatedReport) return
        const headers = ['Report ID', 'Report Type', 'Title', 'Generated At', 'Generated By', 'Reporting Period', 'Scope']
        const row = [
            generatedReport.id,
            generatedReport.reportType,
            `"${generatedReport.title}"`,
            generatedReport.generatedAt,
            `"${generatedReport.generatedBy}"`,
            generatedReport.reportingPeriod,
            `"${generatedReport.scopeDescription}"`,
        ]
        const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), row.join(',')].join('\n')
        const encodedUri = encodeURI(csvContent)
        const link = document.createElement('a')
        link.setAttribute('href', encodedUri)
        link.setAttribute('download', `${generatedReport.id}_report.csv`)
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
    }

    const handleExportJSON = () => {
        if (!generatedReport) return
        const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(generatedReport, null, 2))
        const link = document.createElement('a')
        link.setAttribute('href', dataStr)
        link.setAttribute('download', `${generatedReport.id}_report.json`)
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
    }

    return (
        <div className="rounded-xl border border-ink-200 bg-paper p-5 shadow-xs space-y-5 text-xs">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 border-b border-ink-100 pb-3">
                <div className="space-y-0.5">
                    <div className="flex items-center gap-2">
                        <FileSpreadsheet className="h-4 w-4 text-terracotta-600" />
                        <h3 className="text-sm font-bold text-ink-900">
                            Parliamentary & Executive Report Builder Workspace
                        </h3>
                    </div>
                    <p className="text-[11px] text-ink-500">
                        Generate official statutory dossiers, financial audit digests, and multi-agency acquisition certificates
                    </p>
                </div>

                {onClose && (
                    <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={onClose}
                        className="text-xs font-semibold"
                    >
                        Close Builder
                    </Button>
                )}
            </div>

            {/* Step 1: Select Report Type */}
            <div className="space-y-2">
                <label className="font-bold text-ink-800 block text-xs">
                    1. Select Statutory Report Format:
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5">
                    {REPORT_TYPES.map((rt) => (
                        <button
                            key={rt.type}
                            type="button"
                            onClick={() => setSelectedType(rt.type)}
                            className={`rounded-lg border p-3 text-left transition-all cursor-pointer space-y-1 ${
                                selectedType === rt.type
                                    ? 'border-terracotta-600 bg-terracotta-50/50 shadow-xs'
                                    : 'border-ink-200 bg-paper hover:bg-ink-50/50'
                            }`}
                        >
                            <span className="font-bold text-xs text-ink-900 block truncate">
                                {rt.label}
                            </span>
                            <p className="text-[10px] text-ink-500 leading-snug line-clamp-2">
                                {rt.description}
                            </p>
                        </button>
                    ))}
                </div>
            </div>

            {/* Generate Trigger */}
            <div className="flex items-center justify-between p-3 rounded-lg bg-ink-50/70 border border-ink-200">
                <div className="flex items-center gap-2">
                    <ShieldCheck className="h-4 w-4 text-signal-700" />
                    <span className="text-ink-700 text-xs">
                        Report will apply active query filters (<strong>{filters.period}</strong>, Scope: <strong>{filters.state === 'ALL' ? 'National' : filters.state}</strong>)
                    </span>
                </div>

                <Button
                    type="button"
                    variant="primary"
                    size="sm"
                    onClick={handleGenerate}
                    disabled={generateMutation.isPending}
                    className="flex items-center gap-1.5 text-xs font-semibold cursor-pointer"
                >
                    <FileText className="h-3.5 w-3.5" />
                    <span>{generateMutation.isPending ? 'Compiling Dossier...' : 'Generate Report Preview'}</span>
                </Button>
            </div>

            {/* Step 2: On-Screen Report Preview */}
            {generatedReport && (
                <div className="rounded-xl border border-ink-300 bg-paper p-6 shadow-md space-y-4 text-xs">
                    {/* Official Report Header */}
                    <div className="border-b-2 border-ink-900 pb-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                        <div className="space-y-1">
                            <div className="flex items-center gap-2">
                                <span className="rounded bg-ink-900 px-2 py-0.5 text-[9px] font-mono font-bold text-paper uppercase tracking-wider">
                                    {generatedReport.id}
                                </span>
                                <span className="text-[10px] font-bold text-signal-700 bg-signal-50 px-1.5 py-0.2 rounded border border-signal-200">
                                    VERIFIED OFFICIAL DOSSIER
                                </span>
                            </div>
                            <h2 className="text-base font-bold text-ink-950">
                                {generatedReport.title}
                            </h2>
                            <p className="text-[11px] text-ink-600">
                                Scope: {generatedReport.scopeDescription} • Period: {generatedReport.reportingPeriod}
                            </p>
                        </div>

                        <div className="flex items-center gap-2 shrink-0">
                            <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={handlePrint}
                                className="h-8 px-2.5 text-xs font-semibold flex items-center gap-1 cursor-pointer"
                            >
                                <Printer className="h-3.5 w-3.5 text-ink-600" />
                                <span>Print / PDF</span>
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={handleExportCSV}
                                className="h-8 px-2.5 text-xs font-semibold flex items-center gap-1 cursor-pointer"
                            >
                                <Download className="h-3.5 w-3.5 text-signal-700" />
                                <span>Export CSV</span>
                            </Button>
                            <Button
                                type="button"
                                variant="outline"
                                size="sm"
                                onClick={handleExportJSON}
                                className="h-8 px-2.5 text-xs font-semibold flex items-center gap-1 cursor-pointer"
                            >
                                <Download className="h-3.5 w-3.5 text-ink-600" />
                                <span>JSON</span>
                            </Button>
                        </div>
                    </div>

                    {/* KPI Snapshot Grid */}
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                        {Object.entries(generatedReport.kpiSnapshot).map(([key, val]) => (
                            <div key={key} className="p-3 rounded-lg bg-ink-50/70 border border-ink-200 space-y-0.5">
                                <span className="text-[10px] text-ink-500 font-bold uppercase tracking-wider block truncate">
                                    {key}
                                </span>
                                <span className="font-mono text-sm font-black text-ink-900 block">
                                    {val}
                                </span>
                            </div>
                        ))}
                    </div>

                    {/* Summary Text & Attestation */}
                    <div className="rounded-lg bg-ink-50/50 p-4 border border-ink-100 space-y-2">
                        <span className="font-bold text-ink-900 block text-xs">
                            Executive Attestation & Statutory Finding:
                        </span>
                        <p className="text-ink-800 text-[11px] leading-relaxed">
                            {generatedReport.summaryText}
                        </p>
                        <div className="pt-2 border-t border-ink-100 flex items-center justify-between text-[10px] text-ink-500 font-mono">
                            <span>Compiled by: {generatedReport.generatedBy}</span>
                            <span>Generated: {new Date(generatedReport.generatedAt).toLocaleString('en-IN')}</span>
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
