export const ROUTES = {
  home: '/',
  login: '/login',
  loginOfficer: '/login/officer',
  loginAgency: '/login/agency',
  loginAdmin: '/login/admin',
  register: '/register/officer',
  registerOfficer: '/register/officer',
  registerAgency: '/register/agency',
  piaRegister: '/register/agency',
  dashboard: '/dashboard',
  // Administration
  organizations: '/dashboard/organizations',
  organizationDetail: (id: string) => `/dashboard/organizations/${id}`,
  piaApprovals: '/dashboard/organizations/approvals',
  users: '/dashboard/users',
  userDetail: (id: string) => `/dashboard/users/${id}`,
  // Domain Routes
  projects: '/dashboard/projects',
  projectDetail: (id: string) => `/dashboard/projects/${id}`,
  parcels: '/dashboard/parcels',
  parcelDetail: (id: string) => `/dashboard/parcels/${id}`,
  documents: '/dashboard/documents',
  documentDetail: (id: string) => `/dashboard/documents/${id}`,
  workflow: '/dashboard/workflow',
  workflowDetail: (id: string) => `/dashboard/workflow/${id}`,
  compensation: '/dashboard/compensation',
  compensationDetail: (id: string) => `/dashboard/compensation/${id}`,
  possession: '/dashboard/possession',
  possessionDetail: (id: string) => `/dashboard/possession/${id}`,
  gis: '/dashboard/gis',
  rehabilitation: '/dashboard/rehabilitation',
  rehabilitationDetail: (id: string) => `/dashboard/rehabilitation/${id}`,
  notifications: '/dashboard/notifications',
  analytics: '/dashboard/analytics',
  audit: '/dashboard/audit',
  aiAssistant: '/dashboard/ai-assistant',
  settings: '/dashboard/settings',
} as const;